### ISSUE TITLE
mezzanine_api - Could not import 'rest_framework.filters.DjangoFilterBackend' 

### ISSUE THREAD

**Issue by mike1573** [gcushen/mezzanine-api#19]
Hi, I'm getting;

ImportError: Could not import 'rest_framework.filters.DjangoFilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. AttributeError: 'module' object has no attribute 'DjangoFilterBackend'.

...after completing the installation re http://gcushen.github.io/mezzanine-api/
Appears DjangoFilterBackend is not longer supported in 'rest_framework' but is in 'rest_framework_filters'.
I've tried a number of options to reconfigure but cannot get it to work. How can I fix?

Mezzanine 4.2.3
Django 1.10.8
Python 2.7.6
SQLite 3.8.2

    INSTALLED_APPS = [
        'mezzanine_api',
     #'rest_framework_filters',
        'rest_framework',
        'rest_framework_swagger',
        'oauth2_provider',

Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fdb8fde8410>
Traceback (most recent call last):
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
fn(*args, **kwargs)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/mezzanine/core/management/commands/runserver.py", line 163, in inner_run
super(Command, self).inner_run(*args, **kwargs)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
self.check(display_num_errors=True)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
include_deployment_checks=include_deployment_checks,
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
return checks.run_checks(**kwargs)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
new_errors = check(app_configs=app_configs)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
return check_resolver(resolver)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
for pattern in resolver.url_patterns:
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
return import_module(self.urlconf_name)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/home/mike1573/cart/cart/urls.py", line 13, in 
from cart.apps.api.rest.v1 import views
File "/home/mike1573/cart/cart/apps/api/rest/v1/views.py", line 1, in 
from rest_framework import generics
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/rest_framework/generics.py", line 26, in 
class GenericAPIView(views.APIView):
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/rest_framework/generics.py", line 45, in GenericAPIView
filter_backends = api_settings.DEFAULT_FILTER_BACKENDS
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/rest_framework/settings.py", line 223, in getattr
val = perform_import(val, attr)
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/rest_framework/settings.py", line 168, in perform_import
return [import_from_string(item, setting_name) for item in val]
File "/home/mike1573/cart-env/local/lib/python2.7/site-packages/rest_framework/settings.py", line 184, in import_from_string
raise ImportError(msg)
ImportError: Could not import 'rest_framework.filters.DjangoFilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. AttributeError: 'module' object has no attribute 'DjangoFilterBackend'.

Thanks

**Comment by gcushen** [comment]
@mike1573 thanks for reporting this issue caused by new versions of the API's dependencies.

I'll try to look into it at the weekend. Otherwise, happy to review a PR from anyone who resolves the issue.
