### ISSUE TITLE
can not create mezzanine project with mezzanine-api

### ISSUE THREAD

**Issue by forrestly** [gcushen/mezzanine-api#26]

**Comment by forrestly** [comment]
here is the error message when I run createdb command:


C:\Python27\lib\site-packages\mezzanine\utils\conf.py:65: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 94, in create
    module = import_module(entry)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\django_filters\__init__.py", line 4, in <module>
    from .filterset import FilterSet
  File "C:\Python27\lib\site-packages\django_filters\filterset.py", line 184
    def __init__(self, data=None, queryset=None, *, request=None, prefix=None):
                                                  ^
SyntaxError: invalid syntax

**Comment by gcushen** [comment]
I see that you are using Python 2 which is unsupported (but may possibly still work).

The error can probably be resolved by defining  ALLOWED_HOSTS in your config based on your domain name. This setting is specific to how you are hosting the API. See the mezzanine forums for further support configuring the API.

**Comment by forrestly** [comment]
thanks for your reply, sure ,i use pythonpyt 2.7. but i know mezzanine supported that.

however, i tried to add allow host,but it is not work. i will switch to python 3. thanks again.

在 2018年11月28日，20:18，gcushen <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #26<https://github.com/gcushen/mezzanine-api/issues/26>.
